language: bash
services: docker

env:
  - VERSION=7.1.2-ga3 VARIANT=jdk11-alpine
  - VERSION=7.1.2-ga3 VARIANT=jdk8-alpine

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image="$DOCKER_USERNAME/dockerhub-test:$VERSION-$VARIANT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build --build-arg COMMIT_ID="$TRAVIS_COMMIT" -t "$image" .
      ~/official-images/test/run.sh "$image"
      docker push "$image"
    )

after_script:
  - docker images
