language: bash
services: docker

branches:
  only:
    - dev

env:
  - VERSION=7.1.4-ga5 VARIANT=jdk11-slim

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image="$DOCKER_USERNAME/dockerhub-test:$VERSION-$VARIANT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
      docker push "$image"
    )

after_script:
  - docker images
