language: bash
services: docker

env:
  - VERSION=7.1.2-ga3 VARIANT=jdk8-alpine

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image="dockerhub-test:$VERSION-$VARIANT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images
