language: bash
services: docker

branches:
  only:
    - dev

env:

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image_version="ibaiborodine/dockerhub-test:$VERSION-$VARIANT"
  - image_hash="ibaiborodine/dockerhub-test:$TRAVIS_COMMIT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image_version" .
      ~/official-images/test/run.sh "$image_version"
      docker tag "$image_version" "$image_hash"
      docker push "$image_version"
#      docker push "$image_hash"
    )

after_script:
  - docker images