language: bash
services: docker

branches:
  only:
    - dev

env:
  - VERSION=7.2.7-ga6 VARIANT=jdk8-alpine

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="$DOCKER_USERNAME/dockerhub-test:$VERSION-$VARIANT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      pwd
    )

after_script:
  - docker images
