language: bash
services: docker

branches:
  only:
    - dev

env:
  - VERSION=7.2.7-ga6 VARIANT=jdk8-alpine

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="$DOCKER_USERNAME/dockerhub-test:$VERSION-$VARIANT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      pwd
      docker build -t "$image" "$VERSION/$VARIANT"
      ~/official-images/test/run.sh "$image"
      docker push "$image"
      ./generate-readme.sh "$VERSION-$VARIANT" "$TRAVIS_COMMIT"
      git status
    )

after_script:
  - docker images
