language: bash
services: docker

branches:
  only:
    - dev

env:
  - VERSION=7.0.6-ga7 VARIANT=jdk8-slim
  - VERSION=7.0.6-ga7 VARIANT=jdk8-alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image="ibaiborodine/dockerhub-test:$VERSION-$VARIANT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images