language: bash
services: docker

branches:
  only:
    - dev

env:
  - VERSION=7.3.5-ga9 VARIANT=jdk8-alpine

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image_version="$DOCKER_USERNAME/dockerhub-test:$VERSION-$VARIANT"
  - image_hash="$DOCKER_USERNAME/dockerhub-test:$TRAVIS_COMMIT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image_hash" .
      ~/official-images/test/run.sh "$image_hash"
      docker tag "$image_hash" "$image_version"
      docker push "$image_version"
      docker push "$image_hash"
    )

after_script:
  - docker images