FROM openjdk:PLACEHOLDER

ARG GIT_COMMIT

ENV APP_VERSION PLACEHOLDER

RUN apk add --no-cache \
    bash

COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]

LABEL git_commit=$GIT_COMMIT

CMD ["bash", "-c", "echo APP_VERSION:$APP_VERSION"]
