version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mnt/mysql/conf.d:/etc/mysql/conf.d
      - ./mnt/mysql/initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:6.5.0
    environment:
      - discovery.type=single-node
      - cluster.name=LiferayElasticsearchCluster
      - xpack.security.enabled=false
      - network.bind_host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  liferay:
    image: ibaiborodine/liferay-portal-ce:7.1.3-ga4-jdk11
    depends_on:
      - mysql
      - elasticsearch
    ports:
      - "80:8080"
      - "11311:11311"
    volumes:
      - ./mnt/liferay/base:/etc/opt/liferay
      - lr-data:/opt/liferay/data/document_library

volumes:
  db-data:
  es-data:
  lr-data:
