name: Perform Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release Version
        required: true

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/dockerhub-test
  IMAGE_TAG:  ${{ github.event.inputs.releaseVersion }}

jobs:
  dockerfile:
    name: Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Release Dockerfile
        run: |
          ./script/release-dockerfile.sh -t "$IMAGE_TAG"

      - name: Tag release
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.releaseVersion }}

      - name: Echo tag commit hash
        run: |
          echo "$IMAGE_TAG"
          git show --pretty=format:'%H' --quiet $IMAGE_TAG 

#  docker_image:
#    name: Docker Image
#    runs-on: ubuntu-latest
#    needs: [ dockerfile ]
#
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          ref: "$IMAGE_TAG"
#
#      - uses: actions/checkout@v2
#        with:
#          ref: docker-library/official-images
#          path: official-images
#
#      - name: Build image
#        run: |
#          docker build . --file Dockerfile --tag $IMAGE_NAME:"${IMAGE_TAG//\//-}"
#          ./official-images/test/run.sh $IMAGE_NAME:"${IMAGE_TAG//\//-}"
#          docker tag $IMAGE_NAME:"${IMAGE_TAG//\//-}" $IMAGE_NAME:latest
#
#      - name: Log into registry
#        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
#
#      - name: Push image
#        run: |
#          docker push $IMAGE_NAME:$IMAGE_TAG
#          docker push $IMAGE_NAME:latest
#
#      - name: Update README
#        run: |
#          ./script/generate-readme.sh -t "$IMAGE_TAG" -c "$(git rev-list -n 1 "$IMAGE_TAG")"
#
